version: '3'

volumes:
  pg_data_production:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: v1tox/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: v1tox/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: v1tox/kittygram_gateway
    env_file: .env
    volumes:
      - static:/static/
      - media:/media
    ports:
      - 9000:80
